/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fenetre;

import Entity.User;
import Metier.AllMethods;
import Metier.WriteExcel;
import NMC.MTTC;
import NMC.MTTH;
import NMC.MTTL;
import OPS.MTTA;
import OPS.MTTR;
import com.bmc.arsys.api.ARServerUser;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FileDialog;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.Timer;
import jxl.write.WriteException;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.joda.time.DateTime;

/**
 *
 * @author Vdc_Dsk
 */
public class NMC_IHM extends javax.swing.JFrame {

    ARServerUser ctx;
    public NMC_IHM() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("very.png")));
        this.getRootPane().setDefaultButton(bt_search);
        bt_graph.setEnabled(false);
        bt_excel.setEnabled(false);
        
        grb_GroupRadio.add(rb_NC);
        grb_GroupRadio.add(rb_OPS);
        
        rb_NC.setSelected(true);
        panOPS.setVisible(false);
        
        
        // Text
        txt_mtta.setText("");
        txt_fullName.setText("");
        txt_mttc.setText("");
        txt_mtth.setText("");
        txt_mttl.setText("");
        txt_mttr.setText("");
        
        
        String userName = "NMCnetcool";  
        String userPassword = "Password0123@";
        String serverName = "10.200.172.111";
        ctx = new ARServerUser();  
        ctx.setServer(serverName);  
        ctx.setUser(userName);  
        ctx.setPassword(userPassword);
        try {
            ctx.login();
            cb_allUser.removeAllItems();
            cb_allUser.addItem("Choix du User");
            List<User> allUser = new ArrayList<>();
            allUser = AllMethods.AllUser(ctx);
        for (User user : allUser) {
            cb_allUser.addItem(user.getUserName());  
        }
        } catch (Exception e) {
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateTime1 = new org.joda.time.DateTime();
        grb_GroupRadio = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cb_allUser = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        bt_search = new javax.swing.JButton();
        txt_fullName = new javax.swing.JLabel();
        dt_Start = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dt_End = new com.toedter.calendar.JDateChooser();
        rb_NC = new javax.swing.JRadioButton();
        rb_OPS = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        bt_excel = new javax.swing.JButton();
        panNC = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_mttc = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_mttl = new javax.swing.JLabel();
        txt_mtth = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_nbreTotalTicket = new javax.swing.JLabel();
        txt_nbreClosedTicket = new javax.swing.JLabel();
        panOPS = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_mtta = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_mttr = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        bt_graph = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NMC Workforce");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NMC Workforce");

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Info of Network Controller", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 0, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User Name");

        cb_allUser.setBackground(new java.awt.Color(51, 51, 51));
        cb_allUser.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        cb_allUser.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choisir le User" }));
        cb_allUser.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cb_allUserPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cb_allUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_allUserMouseClicked(evt);
            }
        });
        cb_allUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_allUserActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Her full name is ");

        bt_search.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        bt_search.setText("Search");
        bt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_searchActionPerformed(evt);
            }
        });

        txt_fullName.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        txt_fullName.setForeground(new java.awt.Color(255, 0, 0));
        txt_fullName.setText("ooo");

        dt_Start.setDateFormatString("M/d/yyyy H:mm");
        dt_Start.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Period");

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("to");

        dt_End.setDateFormatString("M/d/yyyy HH:mm:ss a");
        dt_End.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        rb_NC.setBackground(new java.awt.Color(51, 51, 51));
        rb_NC.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        rb_NC.setForeground(new java.awt.Color(255, 255, 255));
        rb_NC.setSelected(true);
        rb_NC.setText("Network Controler");
        rb_NC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_NCActionPerformed(evt);
            }
        });

        rb_OPS.setBackground(new java.awt.Color(51, 51, 51));
        rb_OPS.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        rb_OPS.setForeground(new java.awt.Color(255, 255, 255));
        rb_OPS.setText("Ops");
        rb_OPS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_OPSMouseClicked(evt);
            }
        });
        rb_OPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_OPSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cb_allUser, 0, 130, Short.MAX_VALUE)
                    .addComponent(dt_Start, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txt_fullName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dt_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(rb_NC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE)
                        .addComponent(rb_OPS)))
                .addGap(18, 18, 18)
                .addComponent(bt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(cb_allUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_fullName)
                        .addComponent(bt_search)))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(dt_Start, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addComponent(dt_End, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rb_NC)
                        .addComponent(rb_OPS)))
                .addGap(14, 14, 14))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Summarize the provision of Network Controller");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        bt_excel.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        bt_excel.setText("Open to Excel ");
        bt_excel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_excelActionPerformed(evt);
            }
        });
        jPanel3.add(bt_excel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, -1, -1));

        panNC.setBackground(new java.awt.Color(204, 204, 204));

        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel16.setText("min/ Ticket");

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setText("Mean Time To Log (MTTL) : ");

        txt_mttc.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txt_mttc.setText("jLabel9");

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 204));
        jLabel11.setText("Mean Time To Handover (MTTH) : ");

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel13.setText("min/ Ticket");

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel10.setText("min/ Ticket");

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 204));
        jLabel14.setText("Mean Time To Close (MTTC) : ");

        txt_mttl.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txt_mttl.setText("jLabel9");

        txt_mtth.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txt_mtth.setText("jLabel9");

        jLabel18.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 51));
        jLabel18.setText("Tickets total number  : ");

        jLabel19.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 51));
        jLabel19.setText("Closed ticket total number  : ");

        txt_nbreTotalTicket.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txt_nbreTotalTicket.setText("Nbre");

        txt_nbreClosedTicket.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txt_nbreClosedTicket.setText("Nbre");

        javax.swing.GroupLayout panNCLayout = new javax.swing.GroupLayout(panNC);
        panNC.setLayout(panNCLayout);
        panNCLayout.setHorizontalGroup(
            panNCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panNCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panNCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panNCLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_mttc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panNCLayout.createSequentialGroup()
                        .addGroup(panNCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(panNCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panNCLayout.createSequentialGroup()
                                .addComponent(txt_mttl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10))
                            .addGroup(panNCLayout.createSequentialGroup()
                                .addComponent(txt_mtth)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13))))
                    .addGroup(panNCLayout.createSequentialGroup()
                        .addGroup(panNCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panNCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nbreClosedTicket)
                            .addComponent(txt_nbreTotalTicket))
                        .addGap(75, 75, 75)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panNCLayout.setVerticalGroup(
            panNCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panNCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panNCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_mttl)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(panNCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_mtth)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(panNCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_mttc)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(panNCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txt_nbreTotalTicket))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panNCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txt_nbreClosedTicket))
                .addContainerGap())
        );

        jPanel3.add(panNC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 72, -1, 180));

        panOPS.setBackground(new java.awt.Color(204, 204, 204));

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 204));
        jLabel9.setText("Mean Time To Accept (MTTA) : ");

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 204));
        jLabel12.setText("Mean Time To Resolve (MTTR) : ");

        txt_mtta.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txt_mtta.setText("jLabel9");

        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel15.setText("min/ Ticket");

        txt_mttr.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txt_mttr.setText("jLabel9");

        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel17.setText("min/ Ticket");

        javax.swing.GroupLayout panOPSLayout = new javax.swing.GroupLayout(panOPS);
        panOPS.setLayout(panOPSLayout);
        panOPSLayout.setHorizontalGroup(
            panOPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panOPSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panOPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panOPSLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_mtta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15))
                    .addGroup(panOPSLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_mttr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17))))
        );
        panOPSLayout.setVerticalGroup(
            panOPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panOPSLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panOPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_mtta)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panOPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_mttr)
                    .addComponent(jLabel17))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel3.add(panOPS, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 72, -1, 130));

        bt_graph.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        bt_graph.setText("Graphics");
        bt_graph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_graphActionPerformed(evt);
            }
        });
        jPanel3.add(bt_graph, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 143, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(jLabel1)
                .addContainerGap(282, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(750, 535));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cb_allUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_allUserMouseClicked
        
        
    }//GEN-LAST:event_cb_allUserMouseClicked

    private void cb_allUserPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cb_allUserPopupMenuWillBecomeInvisible
       if(cb_allUser.getSelectedIndex() != 0){
       
        String fullName = AllMethods.User(ctx, cb_allUser.getSelectedItem().toString());
       txt_fullName.setText(fullName);
       } else{
       txt_fullName.setText("");
       }
       
       txt_mttl.setText("");
       txt_mtth.setText("");
       txt_mttc.setText("");
       txt_nbreTotalTicket.setText("");
       txt_nbreClosedTicket.setText("");
       bt_graph.setEnabled(false);
       bt_excel.setEnabled(false);
       
    }//GEN-LAST:event_cb_allUserPopupMenuWillBecomeInvisible
   
    
    
    
    private void bt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_searchActionPerformed
        if(dt_Start.getDate() == null || dt_End.getDate() == null || cb_allUser.getSelectedIndex() == -1 || cb_allUser.getSelectedIndex() == 0 || dt_Start.getDate().after(dt_End.getDate())){
            
            JOptionPane.showMessageDialog(null, "Please complete all fields for the filter or verify date");
        } else {
            DateTime dateJodaStart = new DateTime(dt_Start.getDate());
            DateTime dateJodaEnd = new DateTime(dt_End.getDate());
            String dateStart = dateJodaStart.toString("M/d/yyyy");
            String dateEnd = dateJodaEnd.toString("M/d/yyyy");
//            JOptionPane.showMessageDialog(null, dateEnd);
        //   NMC Network
        if(rb_NC.isSelected()){
            try {
                txt_mttl.setText(String.valueOf(MTTL.moyenneMTTL(cb_allUser.getSelectedItem().toString(), dateStart, dateEnd,txt_nbreTotalTicket, ctx)));
                bt_graph.setEnabled(true);
                bt_excel.setEnabled(true);
            } catch (ArithmeticException e) {
//                JOptionPane.showMessageDialog(null, "Aucun Ticket retouver");
                txt_mttl.setText("0");
                bt_graph.setEnabled(false);
                bt_excel.setEnabled(false);
            } catch (Exception e){
                JOptionPane.showMessageDialog(null, "PROBLEME : " + e.getMessage());
            
            }
            
            try {
                txt_mtth.setText(String.valueOf(MTTH.moyenneMTTH(cb_allUser.getSelectedItem().toString(), dateStart, dateEnd, ctx)));
            } catch (ArithmeticException e) {
//                JOptionPane.showMessageDialog(null, "Aucun Ticket retouver");
                txt_mtth.setText("0");
            } catch (Exception e){
            JOptionPane.showMessageDialog(null, "PROBLEME : " + e.getMessage());
            }
            
            try {
                txt_mttc.setText(String.valueOf(MTTC.moyenneMTTC(cb_allUser.getSelectedItem().toString(), dateStart, dateEnd,txt_nbreClosedTicket, ctx)));
            } catch (ArithmeticException e) {
//                JOptionPane.showMessageDialog(null, "Aucun Ticket retouver");
                txt_mttc.setText("0");
            } catch (Exception e){
                 JOptionPane.showMessageDialog(null, "PROBLEME CLOSED : " + e);
            }
        } 
        
        // OPS
        else if (rb_OPS.isSelected()){
        
        try {
                txt_mttr.setText(String.valueOf(MTTR.moyenneMTTR(txt_fullName.getText(), dateStart, dateEnd, ctx)));
            } catch (ArithmeticException e) {
//                JOptionPane.showMessageDialog(null, "Aucun Ticket retouver");
                txt_mttr.setText("0");
            } catch (Exception e){
            JOptionPane.showMessageDialog(null, "PROBLEME : " + e.getMessage());
            }
            
            try {
                txt_mtta.setText(String.valueOf(MTTA.moyenneMTTA(txt_fullName.getText(), dateStart, dateEnd, ctx)));
            } catch (ArithmeticException e) {
//                JOptionPane.showMessageDialog(null, "Aucun Ticket retouver");
                txt_mtta.setText("0");
            } catch (Exception e){
                 JOptionPane.showMessageDialog(null, "PROBLEME : " + e.getMessage());
            }
        
        }
          
        }
        
        
    }//GEN-LAST:event_bt_searchActionPerformed
String nfile;
    private void bt_excelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_excelActionPerformed
        
        try {
           Metier.WriteExcel writeExcel = new WriteExcel(); 
            FileDialog fd = new FileDialog(NMC_IHM.this, "Save file", FileDialog.SAVE);
            fd.show();
            if(fd.getFile() != null){
            nfile = fd.getDirectory() + fd.getFile() + ".xls"; 
                try {
                   writeExcel.setOutputFile(nfile);
//                   System.out.println("Please check the result file under " + nfile);
                writeExcel.write(Integer.parseInt(txt_mttl.getText()), Integer.parseInt(txt_mtth.getText()), Integer.parseInt(txt_mttc.getText()), dt_Start.getDate().toString()+ " to " + dt_End.getDate().toString());
                Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHeader"+nfile);
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(null, "Nom du fichier existant et ouvert dans un autre processus");
                    } catch (WriteException ex) {
                        JOptionPane.showMessageDialog(null, "Probleme d'ecriture : " + ex.getMessage());
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Nom du fichier existant et ouvert dans un autre processus"); 
                    }
            } 
            } catch (Exception e) {
                   JOptionPane.showMessageDialog(null, "Probleme du write : " + e.getMessage()); 
                }  
    }//GEN-LAST:event_bt_excelActionPerformed

    private void bt_graphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_graphActionPerformed
        try {
            
            if(rb_NC.isSelected()){
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(Double.parseDouble(txt_mttl.getText()), "Temps", "MTTL");
        dataset.setValue(Double.parseDouble(txt_mtth.getText()), "Temps", "MTTH");
        dataset.setValue(Double.parseDouble(txt_mttc.getText()), "Temps", "MTTC");
        JFreeChart chart = ChartFactory.createBarChart("NMC Workforce", "Category", "Times / Min", dataset, PlotOrientation.VERTICAL, false, true, false);
        CategoryPlot categoryPlot = chart.getCategoryPlot();
        categoryPlot.setRangeGridlinePaint(Color.black);
        ChartFrame frame = new ChartFrame("NMC Workforce Graphics for NC", chart);
        frame.setVisible(true);
//        frame.set
        frame.setSize(450, 350);
        
        }
        else if (rb_OPS.isSelected()){
        
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(Double.parseDouble(txt_mtta.getText()), "Temps", "MTTA");
        dataset.setValue(Double.parseDouble(txt_mttr.getText()), "Temps", "MTTR");
        JFreeChart chart = ChartFactory.createBarChart("NMC Workforce", "Category", "Times / Min", dataset, PlotOrientation.VERTICAL, false, true, false);
        CategoryPlot categoryPlot = chart.getCategoryPlot();
        categoryPlot.setRangeGridlinePaint(Color.black);
        ChartFrame frame = new ChartFrame("NMC Workforce Graphics for OPS", chart);
        frame.setVisible(true);
//        frame.set
        frame.setSize(450, 350);
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please complete all fields for the filter or restart");
        }
        
    }//GEN-LAST:event_bt_graphActionPerformed

    private void rb_OPSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_OPSMouseClicked
       
    }//GEN-LAST:event_rb_OPSMouseClicked

    private void rb_OPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_OPSActionPerformed
        panNC.setVisible(false);
        panOPS.setVisible(true);
    }//GEN-LAST:event_rb_OPSActionPerformed

    private void rb_NCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_NCActionPerformed
        panNC.setVisible(true);
        panOPS.setVisible(false);
    }//GEN-LAST:event_rb_NCActionPerformed

    private void cb_allUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_allUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_allUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NMC_IHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NMC_IHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NMC_IHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NMC_IHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
           
        new NMC_IHM().setVisible(true);
             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_excel;
    private javax.swing.JButton bt_graph;
    private javax.swing.JButton bt_search;
    private javax.swing.JComboBox cb_allUser;
    private org.joda.time.DateTime dateTime1;
    private com.toedter.calendar.JDateChooser dt_End;
    private com.toedter.calendar.JDateChooser dt_Start;
    private javax.swing.ButtonGroup grb_GroupRadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panNC;
    private javax.swing.JPanel panOPS;
    private javax.swing.JRadioButton rb_NC;
    private javax.swing.JRadioButton rb_OPS;
    private javax.swing.JLabel txt_fullName;
    private javax.swing.JLabel txt_mtta;
    private javax.swing.JLabel txt_mttc;
    private javax.swing.JLabel txt_mtth;
    private javax.swing.JLabel txt_mttl;
    private javax.swing.JLabel txt_mttr;
    private javax.swing.JLabel txt_nbreClosedTicket;
    private javax.swing.JLabel txt_nbreTotalTicket;
    // End of variables declaration//GEN-END:variables
}
